name: Run tests with Karate DSL

on:
  push:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-run-tests:
    name: Run tests with Karate DSL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Run tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: mvn --batch-mode --update-snapshots verify

      - name: Save report
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: target/karate-reports

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    needs: build-run-tests

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
