name: Run tests with Karate DSL

on:
  push:

concurrency:
  group: tests-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  run-tests:
    name: Run tests with Karate DSL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Run tests
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: mvn --batch-mode --update-snapshots verify
